### ISSUE TITLE
Peer to peer review

### ISSUE THREAD

**Issue by bettercallazamat** [Zubenna/nextweb-clone#2]
## Good work is done. Few improvements to consider:
1. Try to use absolute positioning with relative applied on the parent element
2. The gradient on the logo is not limited to the size of the block
3. Try to use no-repeat when you applying background images
4. Try to use easier ways to make your website responsive like flexbox
5. Apply background gradient when there is text on top of the image
6. Apply hover effects on every link of your page

Please consider these changes and keep the good work!

**Comment by Zubenna** [comment]
All recommendations have been implemented.
